apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog
  namespace: default
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
