apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 446448472447.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newName: 446448472447.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newTag: c0b629b1
resources:
- ../../base
patchesStrategicMerge:
- eks_deployment_patch.yml
- service_patch.yml
