apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newName: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/app
  newTag: 31c994bd
- name: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/web
  newName: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/web
  newTag: 2b609b42
resources:
- ../../base
patchesStrategicMerge:
- eks_deployment_patch.yml
- service_patch.yml
