apiVersion: v1
kind: Service
metadata:
  name: "django-svc"
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: dev
    # env: web
spec:
  selector:
    app: django-blog
