## 서비스
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:                 # type을 생략하여 ClusterIP가 적용된다. 
  clusterIP: 172.20.100.101
  selector:           # service - 백엔드 pod와 연결
    app: mariadb
  ports:
  - name: http
    protocol: TCP
    port: 80
  - name: mysql
    protocol: TCP
    port: 3306

