apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blog
  namespace: default
spec:
  replicas: 3
  selector:           # deployment - pod 대응용
    matchLabels:
      app: django-blog
  template:           # 여기서부터 파드 템플릿
    metadata:
      labels:
        app: django-blog      # 파드의 라벨
    spec:
      #serviceAccountName: irsa-test # IRSA붙임
      containers:
    # django
      - name: web
        image: seongdong/django_blog_web:k8s
        #image: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/web:1.0
        volumeMounts:
        - mountPath: /usr/src/app/_static
          name: static-volume
        - mountPath: /usr/src/app/_media
          name: media-volume
        env:
        - name: DEBUG
          value: "1"
        - name: SECRET_KEY
          value: "')mbk%3ueg))za)h-k@=ir7hzt#i!4much*_pyk=t83$7hy+edi'"
        - name : ALLOWED_HOSTS
          value: "['10.244.2.27', '10.244.2.28', '10.244.2.24', '127.0.0.1']"
        - name: SQL_ENGINE
          value: "django.db.backends.mysql"
        - name : SQL_DATABASE
          value: "do_it_django_prod"
        - name: SQL_USER
          value: "icurfer"
        - name: SQL_PASSWORD
          value: "P@ssw0rd!@"
        - name: SQL_HOST
          value: "127.0.0.1"
        - name: SQL_PORT
          value: "3306"
        ports :
        - containerPort: 8000

        command: ["sh", "-c"]
        args: ["python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && gunicorn django_blog_sdjo.wsgi:application --bind 0.0.0.0:8000"]
    
      - name: nginx
        image: seongdong/django_blog_nginx:local
        #image: 448559955338.dkr.ecr.ap-northeast-2.amazonaws.com/django-nginx:latest
        volumeMounts:
        - mountPath: /usr/src/app/_static
          name: static-volume
        - mountPath: /usr/src/app/_media
          name: media-volume
        ports :
        - containerPort: 80
      
      securityContext:
        runAsUser: 1000

      volumes:
      - name: default
        emptyDir: {}
      - name: mariadb-data
        emptyDir: {}
      - name: static-volume
        persistentVolumeClaim:
          claimName: efs-claim
      - name: media-volume
        persistentVolumeClaim:
          claimName: efs-claim
